# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVisitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsCategory', verbose_name='分类')),
            ],
            options={
                'db_table': 'tb_category_visit_count',
            },
        ),
    ]
